In [7]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/wine.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Wine", axis=1)
y = df["Wine"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (랜덤 포레스트로 변경)
from sklearn.ensemble import RandomForestClassifier

# 랜덤포레스트 분류기 모델 생성 (재현성을 위해 random_state 추가)
model = RandomForestClassifier(random_state=42)


# [4단계] 모델 학습
# 학습용 데이터(X_train, y_train)를 사용해 다수의 의사결정나무 학습 진행
model.fit(X_train, y_train)
print("랜덤 포레스트 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 예측 수행
pred_rf = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_rf)를 비교하여 성능 리포트 출력
print("\n[랜덤 포레스트 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_rf))

데이터 형태 (행, 열): (178, 14)
상위 5개 데이터 미리보기:

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

학습용 데이터 크기: X_train (142, 13), y_train (142,)
테스트용 데이터 크기: X_test (36, 13), y_test (36,)
랜덤 포레스트 모델 학습이 완료되었습니다.

[랜덤 포레스트 분류 성능 평가 리포트]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

In [3]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/wine.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Wine", axis=1)
y = df["Wine"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (로지스틱 회귀로 변경)
from sklearn.linear_model import LogisticRegression

# 로지스틱 회귀 분류기 모델 생성
# (학습 반복 횟수 부족 경고를 방지하기 위해 max_iter=200 설정)
model = LogisticRegression(max_iter=200, random_state=42)


# [4단계] 모델 학습
# 학습용 데이터(X_train, y_train)를 사용해 선형 경계선 학습 진행
model.fit(X_train, y_train)
print("로지스틱 회귀 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 예측 수행
pred_lr = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_lr)를 비교하여 성능 리포트 출력
print("\n[로지스틱 회귀 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_lr))

데이터 형태 (행, 열): (178, 14)
상위 5개 데이터 미리보기:

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

학습용 데이터 크기: X_train (142, 13), y_train (142,)
테스트용 데이터 크기: X_test (36, 13), y_test (36,)
로지스틱 회귀 모델 학습이 완료되었습니다.

[로지스틱 회귀 분류 성능 평가 리포트]
              precision    recall  f1-score   support

           1       1.00      0.93      0.96        14
           2       0.93      1.00      0.97        14
           3       1.00      1.00      1.00         8

    accuracy                           0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [6]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
# 파일이 Google Drive에 있다면, 해당 경로를 사용하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/wine.csv") # 예시 경로

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Wine", axis=1)
y = df["Wine"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (KNN으로 변경)
from sklearn.neighbors import KNeighborsClassifier

# KNN(K-최근접 이웃) 분류기 모델 생성
model = KNeighborsClassifier()


# [4단계] 모델 학습
# KNN은 별도의 복잡한 수식 학습 없이, 학습 데이터를 기억(저장)해두는 방식으로 작동합니다.
model.fit(X_train, y_train)
print("KNN 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 예측 수행
pred_knn = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_knn)를 비교하여 성능 리포트 출력
print("\n[KNN 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_knn))

데이터 형태 (행, 열): (178, 14)
상위 5개 데이터 미리보기:

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

학습용 데이터 크기: X_train (142, 13), y_train (142,)
테스트용 데이터 크기: X_test (36, 13), y_test (36,)
KNN 모델 학습이 완료되었습니다.

[KNN 분류 성능 평가 리포트]
              precision    recall  f1-score   support

           1       0.86      0.86      0.86        14
           2       0.79      0.79      0.79        14
           3       0.38      0.38      0.38         8

    accuracy                           0.72        36
   macro avg       0.67      0.67      0.67        36
weighted avg       0.72      0.72      0.72        36

In [8]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd
import numpy as np

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/wine.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Wine", axis=1)
y = df["Wine"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 회귀 모델 객체 생성 (제시해주신 코드 반영)
from sklearn.tree import DecisionTreeRegressor

# 의사결정나무 회귀 모델 생성 (재현성을 위해 random_state 추가)
model = DecisionTreeRegressor(random_state=42)


# [4단계] 모델 학습 (제시해주신 코드 반영)
model.fit(X_train, y_train)
print("의사결정나무 회귀 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 회귀 성능 평가 (제시해주신 코드 반영)
from sklearn.metrics import mean_squared_error

# 테스트용 데이터(X_test)를 이용해 수치 예측 수행
dy_preds = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(dy_preds)를 비교하여 RMSE(평균제곱근오차) 계산
mse = np.sqrt(mean_squared_error(dy_preds, y_test))
print('평균제곱근오차(RMSE):', mse)

데이터 형태 (행, 열): (178, 14)
상위 5개 데이터 미리보기:

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

학습용 데이터 크기: X_train (142, 13), y_train (142,)
테스트용 데이터 크기: X_test (36, 13), y_test (36,)
의사결정나무 회귀 모델 학습이 완료되었습니다.
평균제곱근오차(RMSE): 0.408248290463863

In [9]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd
import numpy as np

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/wine.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Wine", axis=1)
y = df["Wine"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 회귀 모델 객체 생성 (제시해주신 코드 반영)
from sklearn.tree import DecisionTreeRegressor

# 의사결정나무 회귀 모델 생성 (재현성을 위해 random_state 추가)
model = DecisionTreeRegressor(random_state=42)


# [4단계] 모델 학습 (제시해주신 코드 반영)
model.fit(X_train, y_train)
print("의사결정나무 회귀 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 회귀 성능 평가 (제시해주신 코드 반영)
from sklearn.metrics import mean_squared_error

# 테스트용 데이터(X_test)를 이용해 수치 예측 수행
dy_preds = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(dy_preds)를 비교하여 RMSE(평균제곱근오차) 계산
mse = np.sqrt(mean_squared_error(dy_preds, y_test))
print('평균제곱근오차(RMSE):', mse)

데이터 형태 (행, 열): (178, 14)
상위 5개 데이터 미리보기:

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

학습용 데이터 크기: X_train (142, 13), y_train (142,)
테스트용 데이터 크기: X_test (36, 13), y_test (36,)
의사결정나무 회귀 모델 학습이 완료되었습니다.
평균제곱근오차(RMSE): 0.408248290463863