In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report


df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/iris.csv")

X = df.drop("species", axis=1)
y = df["species"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

pred_dt = model.predict(X_test)
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       0.92      1.00      0.96        12
   virginica       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

In [6]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'iris.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/iris.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("species", axis=1)
y = df["species"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (KNN 분류기)
from sklearn.neighbors import KNeighborsClassifier

# K-최근접 이웃 모델 생성 (기본 이웃 수 k=5)
model = KNeighborsClassifier()


# [4단계] 모델 학습
# KNN은 별도의 수학적 방정식 학습 없이 데이터를 저장해두는 방식으로 작동합니다.
model.fit(X_train, y_train)
print("KNN 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 붓꽃 품종 예측 수행
pred_knn = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_knn)를 비교하여 성능 리포트 출력
print("\n[KNN 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_knn))

데이터 형태 (행, 열): (150, 5)
상위 5개 데이터 미리보기:

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

학습용 데이터 크기: X_train (120, 4), y_train (120,)
테스트용 데이터 크기: X_test (30, 4), y_test (30,)
KNN 모델 학습이 완료되었습니다.

[KNN 분류 성능 평가 리포트]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [7]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'iris.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/iris.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("species", axis=1)
y = df["species"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (로지스틱 회귀 적용)
from sklearn.linear_model import LogisticRegression

# 로지스틱 회귀 분류기 모델 생성
# (학습 반복 횟수 경고를 방지하기 위해 max_iter=200 설정 및 재현성을 위한 random_state 추가)
model = LogisticRegression(max_iter=200, random_state=42)


# [4단계] 모델 학습
# 학습용 데이터(X_train, y_train)를 사용해 선형 경계선 학습 진행
model.fit(X_train, y_train)
print("로지스틱 회귀 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 품종 예측 수행
pred_lr = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_lr)를 비교하여 성능 리포트 출력
print("\n[로지스틱 회귀 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_lr))

데이터 형태 (행, 열): (150, 5)
상위 5개 데이터 미리보기:

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

학습용 데이터 크기: X_train (120, 4), y_train (120,)
테스트용 데이터 크기: X_test (30, 4), y_test (30,)
로지스틱 회귀 모델 학습이 완료되었습니다.

[로지스틱 회귀 분류 성능 평가 리포트]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [8]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'iris.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/iris.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("species", axis=1)
y = df["species"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (랜덤 포레스트 적용)
from sklearn.ensemble import RandomForestClassifier

# 랜덤 포레스트 분류기 모델 생성 (재현성을 위한 random_state 추가)
model = RandomForestClassifier(random_state=42)


# [4단계] 모델 학습
# 학습용 데이터(X_train, y_train)를 사용해 다수의 의사결정나무 학습 진행
model.fit(X_train, y_train)
print("랜덤 포레스트 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 품종 예측 수행
pred_rf = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_rf)를 비교하여 성능 리포트 출력
print("\n[랜덤 포레스트 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_rf))

데이터 형태 (행, 열): (150, 5)
상위 5개 데이터 미리보기:

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

학습용 데이터 크기: X_train (120, 4), y_train (120,)
테스트용 데이터 크기: X_test (30, 4), y_test (30,)
랜덤 포레스트 모델 학습이 완료되었습니다.

[랜덤 포레스트 분류 성능 평가 리포트]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30