In [ ]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
# 'Outcome' 컬럼이 당뇨 여부(정답)를 나타냅니다 (0 또는 1).
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성
from sklearn.tree import DecisionTreeClassifier

# 의사결정나무 분류기 모델 생성
model = DecisionTreeClassifier(random_state=42)


# [4단계] 모델 학습
# 학습용 데이터(X_train, y_train)를 사용해 패턴 학습 진행
model.fit(X_train, y_train)
print("모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 예측 수행
pred_dt = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_dt)를 비교하여 성능 리포트 출력
print("\n[분류 성능 평가 리포트]")
print(classification_report(y_test, pred_dt))

데이터 형태 (행, 열): (768, 9)
상위 5개 데이터 미리보기:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

학습용 데이터 크기: X_train (614, 8), y_train (614,)
테스트용 데이터 크기: X_test (154, 8), y_test (154,)
모델 학습이 완료되었습니다.

[분류 성능 평가 리포트]
              precision    recall  f1-score   support

           0       0.83      0.76      0.79        99
           1       0.62      0.73      0.67        55

    accuracy                           0.75       154
   macro avg       0.73      0.74      0.73       154
weighted avg       0.76      0.75      0.75       154

In [ ]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (랜덤 포레스트로 변경)
from sklearn.ensemble import RandomForestClassifier

# 랜덤포레스트 분류기 모델 생성 (재현성을 위해 random_state 추가)
model = RandomForestClassifier(random_state=42)


# [4단계] 모델 학습
# 학습용 데이터(X_train, y_train)를 사용해 다수의 의사결정나무 학습 진행
model.fit(X_train, y_train)
print("랜덤 포레스트 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 예측 수행
pred_rf = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_rf)를 비교하여 성능 리포트 출력
print("\n[랜덤 포레스트 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_rf))

데이터 형태 (행, 열): (768, 9)
상위 5개 데이터 미리보기:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

학습용 데이터 크기: X_train (614, 8), y_train (614,)
테스트용 데이터 크기: X_test (154, 8), y_test (154,)
랜덤 포레스트 모델 학습이 완료되었습니다.

[랜덤 포레스트 분류 성능 평가 리포트]
              precision    recall  f1-score   support

           0       0.79      0.78      0.78        99
           1       0.61      0.62      0.61        55

    accuracy                           0.72       154
   macro avg       0.70      0.70      0.70       154
weighted avg       0.72      0.72      0.72       154

In [ ]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (로지스틱 회귀로 변경)
from sklearn.linear_model import LogisticRegression

# 로지스틱 회귀 분류기 모델 생성
# (학습 반복 횟수 부족 경고를 방지하기 위해 max_iter=200 설정)
model = LogisticRegression(max_iter=200, random_state=42)


# [4단계] 모델 학습
# 학습용 데이터(X_train, y_train)를 사용해 선형 경계선 학습 진행
model.fit(X_train, y_train)
print("로지스틱 회귀 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 예측 수행
pred_lr = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_lr)를 비교하여 성능 리포트 출력
print("\n[로지스틱 회귀 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_lr))

데이터 형태 (행, 열): (768, 9)
상위 5개 데이터 미리보기:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

학습용 데이터 크기: X_train (614, 8), y_train (614,)
테스트용 데이터 크기: X_test (154, 8), y_test (154,)
로지스틱 회귀 모델 학습이 완료되었습니다.

[로지스틱 회귀 분류 성능 평가 리포트]
              precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154

In [ ]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 모델 객체 생성 (KNN으로 변경)
from sklearn.neighbors import KNeighborsClassifier

# KNN(K-최근접 이웃) 분류기 모델 생성
model = KNeighborsClassifier()


# [4단계] 모델 학습
# KNN은 별도의 복잡한 수식 학습 없이, 학습 데이터를 기억(저장)해두는 방식으로 작동합니다.
model.fit(X_train, y_train)
print("KNN 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 성능 평가
from sklearn.metrics import classification_report

# 테스트용 데이터(X_test)를 이용해 예측 수행
pred_knn = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(pred_knn)를 비교하여 성능 리포트 출력
print("\n[KNN 분류 성능 평가 리포트]")
print(classification_report(y_test, pred_knn))

데이터 형태 (행, 열): (768, 9)
상위 5개 데이터 미리보기:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

학습용 데이터 크기: X_train (614, 8), y_train (614,)
테스트용 데이터 크기: X_test (154, 8), y_test (154,)
KNN 모델 학습이 완료되었습니다.

[KNN 분류 성능 평가 리포트]
              precision    recall  f1-score   support

           0       0.75      0.71      0.73        99
           1       0.52      0.58      0.55        55

    accuracy                           0.66       154
   macro avg       0.64      0.64      0.64       154
weighted avg       0.67      0.66      0.67       154

In [36]:
# [1단계] 데이터 불러오기 및 전처리
import pandas as pd
import numpy as np

# 코랩 환경에 'diabetes.csv' 파일을 업로드한 후 실행하세요.
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")

# 독립 변수(X)와 타겟 변수(y) 분리
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

print("데이터 형태 (행, 열):", df.shape)
print("상위 5개 데이터 미리보기:")
display(df.head())


# [2단계] 데이터셋 분할 (학습용 / 테스트용)
from sklearn.model_selection import train_test_split

# 전체 데이터 중 80%는 학습용, 20%는 테스트용으로 분할 (재현성을 위해 random_state 설정)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"학습용 데이터 크기: X_train {X_train.shape}, y_train {y_train.shape}")
print(f"테스트용 데이터 크기: X_test {X_test.shape}, y_test {y_test.shape}")


# [3단계] 회귀 모델 객체 생성 (제시해주신 코드 반영)
from sklearn.tree import DecisionTreeRegressor

# 의사결정나무 회귀 모델 생성 (재현성을 위해 random_state 추가)
model = DecisionTreeRegressor(random_state=42)


# [4단계] 모델 학습 (제시해주신 코드 반영)
model.fit(X_train, y_train)
print("의사결정나무 회귀 모델 학습이 완료되었습니다.")


# [5단계] 예측 및 회귀 성능 평가 (제시해주신 코드 반영)
from sklearn.metrics import mean_squared_error

# 테스트용 데이터(X_test)를 이용해 수치 예측 수행
dy_preds = model.predict(X_test)

# 실제 정답(y_test)과 예측 결과(dy_preds)를 비교하여 RMSE(평균제곱근오차) 계산
mse = np.sqrt(mean_squared_error(dy_preds, y_test))
print('평균제곱근오차(RMSE):', mse)

데이터 형태 (행, 열): (768, 9)
상위 5개 데이터 미리보기:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

학습용 데이터 크기: X_train (614, 8), y_train (614,)
테스트용 데이터 크기: X_test (154, 8), y_test (154,)
의사결정나무 회귀 모델 학습이 완료되었습니다.
평균제곱근오차(RMSE): 0.5032362797401965